services:
  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_DATABASE=test_db'
      - 'MYSQL_USER=admin'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=root_password'

  redis:
    image: redis:7.2.5
    restart: always
    ports:
      - '6379:6379'
